
service: sns-example

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    TOPIC_ARN:
      Ref: SNSTopic

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "SNS:Publish"
      Resource:
        Ref: SNSTopic

functions:
  hello:
    handler: handler.publishToSNS
    events:
      - http:
          path: publishToSNS
          method: post

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: "Test-Topic"
